# Generated by Django 3.1 on 2020-09-12 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('num_followers', models.IntegerField(default=0)),
                ('stage', models.IntegerField(default=1)),
                ('line1', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=20)),
                ('zipcode', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lead_step_id', models.IntegerField(default=0)),
                ('scope', models.CharField(choices=[('local', 'local'), ('state', 'state'), ('country', 'country')], max_length=7)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('statement', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('office_id', models.IntegerField(default=0)),
                ('first', models.CharField(default='', max_length=200)),
                ('last', models.CharField(default='', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('persona', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='forward_app.persona')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_comment_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('politician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forward_app.politician')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forward_app.policy')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('next_step_id', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forward_app.plan')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Stance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forward_app.policy')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forward_app.politician')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='politician',
            name='policies',
            field=models.ManyToManyField(through='forward_app.Stance', to='forward_app.Policy'),
        ),
        migrations.AddField(
            model_name='plan',
            name='politician',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='forward_app.politician'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('next_comment_id', models.IntegerField(default=0)),
                ('content', models.CharField(blank=True, default='', max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forward_app.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fundraised', models.IntegerField(default=0)),
                ('fundraise_goal', models.IntegerField(default=0)),
                ('actblue', models.URLField(default='')),
                ('politician', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='forward_app.politician')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forward_app.constituency'),
        ),
        migrations.AddField(
            model_name='thread',
            name='popularity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forward_app.popularity'),
        ),
    ]
