# Generated by Django 3.0.8 on 2020-07-29 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forward_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('statement', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forward_app.Policy')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('endrorsements', models.IntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('popularity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forward_app.Popularity')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
