# Generated by Django 3.0.8 on 2020-07-30 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forward_app', '0002_comment_policy_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_comment_id', models.IntegerField()),
                ('popularity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forward_app.Popularity')),
            ],
        ),
    ]
