# Generated by Django 3.1 on 2020-08-05 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forward_app', '0002_auto_20200805_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='users',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
