# Generated by Django 3.1 on 2020-08-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forward_app', '0004_auto_20200804_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='followers',
            new_name='num_followers',
        ),
    ]
